// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHcXezMfFZKu3rEQhHzIcEkViuDFUNb0o',
    appId: '1:533886545260:web:05d58c3e975ee7ee439749',
    messagingSenderId: '533886545260',
    projectId: 'stickeep',
    authDomain: 'stickeep.firebaseapp.com',
    databaseURL: 'https://stickeep-default-rtdb.firebaseio.com',
    storageBucket: 'stickeep.firebasestorage.app',
    measurementId: 'G-R1CXSG66JH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPWQOEbGwG_4lh3JS1a0F2L3ZGV8Pw8o0',
    appId: '1:533886545260:android:f19f2627501af76c439749',
    messagingSenderId: '533886545260',
    projectId: 'stickeep',
    databaseURL: 'https://stickeep-default-rtdb.firebaseio.com',
    storageBucket: 'stickeep.firebasestorage.app',
  );
}
